# Generated by Django 5.0.1 on 2024-01-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investApi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stoks",
            name="price",
            field=models.DecimalField(
                decimal_places=7, default=0, max_digits=7, verbose_name="Цена"
            ),
        ),
    ]
