# Generated by Django 5.0.1 on 2024-01-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investApi", "0002_alter_stoks_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stoks",
            name="capitalisation",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=16, verbose_name="Капитализация"
            ),
        ),
        migrations.AlterField(
            model_name="stoks",
            name="price_change",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Изменение День %",
            ),
        ),
        migrations.AlterField(
            model_name="stoks",
            name="volume",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=16, verbose_name="Объём"
            ),
        ),
    ]
