# Generated by Django 5.0.1 on 2024-01-20 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "investApi",
            "0003_alter_stoks_capitalisation_alter_stoks_price_change_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Stoks",
            new_name="Stock",
        ),
    ]
