# Generated by Django 5.0.1 on 2024-01-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investApi", "0004_rename_stoks_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="title",
            field=models.TextField(max_length=20, unique=True, verbose_name="Название"),
        ),
    ]
