# Generated by Django 5.0.1 on 2024-01-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investApi", "0005_alter_stock_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="price",
            field=models.DecimalField(
                decimal_places=7, default=0, max_digits=14, verbose_name="Цена"
            ),
        ),
    ]
